apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: traefik
    version: 35.4.0
    repository: https://traefik.github.io/charts