traefik:
  ingressRoute:
    dashboard:
      enabled: true
      matchRule: Host(`traefik.web`)
      entryPoints:
        - web
  providers:
    kubernetesGateway:
      enabled: true
  gateway:
    namespacePolicy: All
    listeners:
      web:
        port: 80
  additionalArguments:
    - "--api.dashboard=true"
    - "--log.level=INFO"
  ports:
    web:
      port: 80
    websecure:
      port: 443