kube-prometheus-stack:
#  crds:
#    enabled: false

  prometheus:
    service:
     type: LoadBalancer
     loadBalancerIP: 192.168.56.103
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false
      scrapeConfigSelectorNilUsesHelmValues: false
      scrapeInterval: 15s
      evaluationInterval: 15s
      enableAdminAPI: true

  alertmanager:
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.56.105
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - alertmanager.web
      paths:
        - /

  grafana:
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.56.104
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - grafana.web